name: Update requirements

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install pipreqs

    - name: Generate requirements
      run: |
        pipreqs . --force

    - name: Commit and push changes
      uses: actions/github-script@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git push
