name: Check and update requirements

on:
  push:
    branches:
      - main

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pipreqs

    - name: Generate requirements.txt
      run: |
        source venv/bin/activate
        pipreqs --force .

    - name: Commit changes
      if: steps.generate_requirements.outputs.changed == 'True'
      uses: actions/github-script@v3
      with:
        script: |
          git config --local user.email "github-actions[at]github.com"
          git config --local user.name "GitHub Actions"
          git add requirements.txt
          git diff --cached --exit-code || git commit -m "Update requirements.txt"
          git push origin main
